### ISSUE TITLE
Flares after 2020

### ISSUE THREAD

**Issue by a-e-egorov** [nplutino/FlareList#1]
It would be good to have opportunity to load flares after 2020 till current moment.

**Comment by nplutino** [comment]
The catalog has been extended by my colleagues.

The most recent version can be found at:
https://doi.org/10.5281/zenodo.10560188

**Comment by a-e-egorov** [comment]
Ok, thanks a lot!

**Comment by a-e-egorov** [comment]
Ok, thanks a lot!

**Comment by a-e-egorov** [comment]
Regular updates of the catalog are really useful..
